---
- name: Ping from MikroTik router
  hosts: mikrotik
  gather_facts: no  # MUST be off
  tasks:
    - name: Run ping command via raw
      raw: "/tool ping 8.8.8.8 count=4"
      register: result

    - name: Show ping result
      debug:
        var: result.stdout
