---
- name: Ping MikroTik router
  hosts: mikrotik
  gather_facts: no
  tasks:
    - name: Ping 8.8.8.8 from MikroTik
      raw: "/ping 8.8.8.8 count=4"
      register: ping_output

    - name: Display ping results
      debug:
        var: ping_output.stdout
