---
- name: Ping server 100 times
  hosts: all
  become: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.12

  tasks:
    - name: Send 100 ICMP ping packets to the server
      command: ping -c 100 12.1.0.14
      register: ping_result
      ignore_errors: yes

    - name: Show ping output
      debug:
        var: ping_result.stdout
