---
- name: List upgradable packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Show list of upgradable packages
      shell: apt list --upgradable
      register: upgrade_output

    - name: Print list of upgradable packages
      debug:
        var: upgrade_output.stdout_lines
