---
- name: Force update and upgrade Ubuntu packages using shell
  hosts: all
  become: yes
  tasks:

    - name: Update package list
      shell: apt update -y
      register: update_output
      ignore_errors: true

    - name: Upgrade all available packages
      shell: apt full-upgrade -y
      register: upgrade_output
      ignore_errors: true

    - name: Autoremove unused packages
      shell: apt autoremove -y

    - name: Autoclean package cache
      shell: apt autoclean -y

    - name: Reboot if kernel or system packages were upgraded
      reboot:
        msg: "System rebooting after forced upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: uptime

    - name: Show upgrade result
      debug:
        var: upgrade_output.stdout_lines
