---
- name: Upgrade all available packages on Ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Perform full upgrade (includes kernel and dependencies)
      apt:
        upgrade: full

    - name: Remove unnecessary packages
      apt:
        autoremove: yes

    - name: Clean up local apt cache
      apt:
        autoclean: yes

    - name: Reboot if required (e.g., after kernel upgrade)
      reboot:
        msg: "Rebooting to complete full upgrade"
        connect_timeout: 5
        reboot_timeout: 600
        test_command: uptime
