---
- name: Update and upgrade Ubuntu servers
  hosts: all   # <-- match the group name in your inventory
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        lock_timeout: 300
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      become: yes

