---
- name: Fully update and upgrade Ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Ensure the apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Only refresh if older than 1 hour

    - name: Upgrade all packages (equivalent to apt full-upgrade)
      apt:
        upgrade: full

    - name: Autoremove unused packages
      apt:
        autoremove: yes

    - name: Clean local repository of retrieved package files
      apt:
        autoclean: yes
