---
- name: Update and upgrade Ubuntu servers
  hosts: SERVERS 
  become: all
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      become: yes
