---
- name: Update Ubuntu packages without reboot
  hosts: your_ubuntu_servers
  become: yes
  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages without reboot
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
