---
- name: List and perform upgrades on Debian servers (no reboot)
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: List available package upgrades
      ansible.builtin.shell: apt list --upgradable 2>/dev/null | tail -n +2
      register: upgrade_list
      changed_when: false

    - name: Show available upgrades
      ansible.builtin.debug:
        var: upgrade_list.stdout_lines

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600   # don’t refresh if cache is recent (optional)

    - name: Perform full upgrade
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes          # remove unused deps (optional)
