---
- name: List and perform upgrades on Debian servers (no reboot)
  hosts: all
  become: true
  gather_facts: yes

  tasks:
    - name: List available package upgrades
      ansible.builtin.command: apt list --upgradable
      register: upgrade_list
      changed_when: false

    - name: Show available upgrades
      ansible.builtin.debug:
        var: upgrade_list.stdout_lines

    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: full
